name: Test on pull request or merge to main

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Check Chrome version
      run: google-chrome --version

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Install Allure
      run: |
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz | tar -xz -C /opt/
        sudo ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest
      continue-on-error: true

    - name: Generate Allure report
      run: |
        source venv/bin/activate
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
